#' @title Define the model for smooth PRC using LMMsolver (Boer 2023)
#' @inheritParams LMMsolver::LMMsolve
#' @param splineH0 As spline but for the null model. Default: a one dimensional
#' smooth in time.
#' \code{~ spl1D(time, nseg = 6, degree = 3, pord = 2)}
#' See \code{\link[LMMsolver]{LMMsolve}}.
#' @param fixedH0 The default is \code{Yb~1}. Usually
#' equal to fixed. NB: the response variable needs to be \code{Yb}, a
#  variable internally generated by \code{Y%*%b} with \code{Y} the abundance
#' variable internally generated from the abundance table \code{Y} and
#  and \code{b}, the species
#' loading vector that is optimized.
#' The default is \code{Yb~1}.
#' @param start_time numeric time of the start of the treatment application.
#' Default: \code{0}.
#' @param treatment.level.as.quantity logical. Default \code{TRUE} for an
#' analysis using a 2d spline. If \code{FALSE}, the default spline model is
#' replaced by default to one containing 1d splines, one 1d-spline for each
#' level.
#' @param pord named integer vector of the difference order of the
#' spline penalty.
#' Default: \code{c(time =2, dose= 2, time.overall= 3, Treatment = 2)},
#' where the first two orders are used only with
#'  \code{treatment.level.as.quantity} is \code{TRUE}
#'  and the last two with  \code{treatment.level.as.quantity} is \code{FALSE}.
#'@param nseg named integer vector of number of segments in P-splines,
#' can be large.
#'  Default \code{ c(time = 6, dose = 6)}.
#'@param degree degree of the B-splines. Default \code{3}.
#' @references
#' Boer, Martin P. 2023.
#' Tensor Product P-Splines Using a Sparse Mixed Model Formulation.
#' Statistical Modelling 23 (5-6): 465–79.
#' \doi{10.1177/1471082X231178591}
#'
#' @details
#'  An atypical aspect of the function is that the time and treatment factors
#'  need to have the names Time and Treatment in \code{data}, \emph{i.e.}
#'  \code{set_smoothPRC_model} assumes that the data contain two factor or
#'   character variables
#'  \code{Time} and \code{Treatment} that can be converted to  the numeric
#'   variables \code{time} and \code{dose}, respectively, using
#'  \code{\link{fvalues4levels}}. The values of \code{dose} are set to 0 for
#'  negative values of \code{time} and \code{time ==0},
#'  after subtraction of \code{start_time}.
#'  In this case, the default spline model is:
#'  \code{ ~ spl2D(time, dose,  = c(6, 6), degree = 3, pord = 2)}.
#'  To enable \code{Treatment} to be treated as a factor (instead of as a
#'  quantitative variable), the function also generates variables with
#'  names \code{D1}, ..., \code{D}\emph{k}, with \emph{k} the number of
#'  treatments beyond the reference treatment,
#'  if \code{treatment.level.as.quantity} is \code{TRUE}.
#'  These variables contain the time
#'  since the start of the experiment for each treatment.
#'  An example of the formula for \code{spline}
#'  when \code{treatment.level.as.quantity} is \code{FALSE}
#'  and the number of levels of \code{Treatment} is 4,  is
#'  \code{spl1D(time, nseg =6, degree = 3, pord = 3)+
#'  spl1D(D1, nseg = 6, degree = 3, pord = 2)+
#'  spl1D(D2, nseg = 6, degree = 3, pord = 2)+
#'  spl1D(D3, nseg = 6, degree = 3, pord = 2)}.
#'  This is the default model
#'  if \code{treatment.level.as.quantity} is \code{FALSE}.
#' The default spline model assumes that the Treatment factor has a quantitative
#' basis, so that the response to Time and Treatment can be analyzed using a
#' 2D spline model.
#' @example demo/smoothPRC_SimData.r
#' @example demo/smoothPRC_Ossenkampen.r
#' @seealso \code{\link{smoothPRC}}
#' @export

set_smoothPRC_model <-
  function(spline = NULL,
           splineH0 = ~ spl1D(time, nseg = 6, degree = 3, pord = 2),
           fixed = Yb ~ 1,
           fixedH0= fixed,
           random = NULL, residual = NULL, weights= NULL,
           treatment.level.as.quantity = TRUE,
           pord = c(time = 2, dose = 2, time.overall = 3, Treatment = 2),
           nseg =  c(time = 6, dose = 6),
           degree =3,
           start_time = 0,data){
    #data with Time and Treatment as factors, modified here to quantitative time and dose
    # pretimes dose to 0
    # start_time = numeric value or vector of length(nrow(data))
    # NB: time = 0 is treated as control (pre-treatment condition).

    if (!is.factor(data$Time)) data$Time <- factor(data$Time)
    if (!is.factor(data$Treatment)) data$Treatment <- factor(data$Treatment)
    valsTime<- PRC::fvalues4levels(data, "Time")
    data$time <- valsTime[data$Time] - start_time
    valsTreatment<- PRC::fvalues4levels(data, "Treatment")
    if (all(valsTreatment == seq_along(valsTreatment))) valsTreatment <- valsTreatment-1
    data$dose <- valsTreatment[data$Treatment]
    data$dose  <- ifelse(data$time>0, data$dose, 0)
    if (!treatment.level.as.quantity) {
      datI <- model.matrix(~ time + Treatment:time, data = data)[,-c(1,2)]

      datI <- as.data.frame(datI)
      idsl <- 1:(nlevels(data$Treatment)-1)
      names(datI) <- paste0("D", idsl)
      if(!is.null(splineH0) && is.null(spline)){
        spline <- paste0("~spl1D(time, nseg =",
                      nseg[1],", degree =", degree[1],", pord = ", pord[3],")")
        txt<-  paste("spl1D(D",idsl,", nseg=",
                      nseg[2],", degree =", degree[1],", pord =", pord[4],")",
                      collapse = "+",sep ="")
        spline <- as.formula(paste0(spline,"+",txt))
      }
      datI[data$time <= 0, ] <- 0
      data <- cbind(data,datI)
    } else {
      if(!is.null(splineH0) && is.null(spline))spline <- as.formula(paste0("~ spl2D(time, dose, nseg = c(",
                                  nseg[1],",",nseg[2],"), degree =", degree[1],", pord = ", pord[2],")"))
    }
    # sets LMMsolver_model with response in formulafixed and data : Design
    dat0 <- data
    dat0$dose <- 0
    dat0$Treatment <- levels(data$Treatment)[1]
    if("D1" %in% names(dat0)) {
      id <- which(names(dat0) %in% "D1")
      dat0[, id : ncol(dat0)] <- 0
    }


    out <- list(spline,splineH0,fixed, fixedH0, random, residual, weights, as.data.frame(dat0), as.data.frame(data))
    names(out) = c("spline","splineH0","fixed","fixedH0", "random", "residual", "weights", "dat0","data")
    return(out)
  }

